pool_info:
  default_res: Rose Garden
  name: Rose Garden
  logo_url: https://www.chia.net/img/chia_logo.svg
  description: (example) Rose Garden allows you to pool with low fees, paying out daily using XCR.
welcome_message: 'Welcome to rose garden!'
pool_fee: 0.01
pool_url: http://10.0.0.45:18520
min_difficulty: 10
default_difficulty: 10
default_target_address: xcr1jzjznzj8yt3tux5pph4l0gg7eep92upvthv8jfdcdndlwg4q9xlq4uv63y
pool_fee_address: xcr1jzjznzj8yt3tux5pph4l0gg7eep92upvthv8jfdcdndlwg4q9xlq4uv63y
wallet_fingerprint: 1136084163
authentication_token_timeout: 5
wallet_id: 1
node_rpc_port: 8025
wallet_rpc_port: 9520
partial_time_limit: 25
partial_confirmation_delay: 300
scan_start_height: 1000
collect_pool_rewards_interval: 600
confirmation_security_threshold: 32
payment_interval: 600
max_additions_per_transaction: 400
number_of_partials_target: 300
time_target: 86400
relative_lock_height: 32
logging:
  log_path: /var/log/chia
  log_filename: pool-server.log
  log_level: INFO
  log_maxfilesrotation: 7
  log_stdout: false
server:
  server_host: 0.0.0.0
  server_port: 18520
  server_use_ssl: false
  server_ssl_crt: config/ssl/domain/domain_srv.crt
  server_ssl_key: config/ssl/domain/domain_srv.key
poollimit:
  enable_whitelist: true
  white_list:
    'xcr1lh5k8uvqxvtdutauxpust8d4fycl4h7r27tqvmhz2ekhezvqkevsk7wxjk': 0
    '0x847f8da6eef5dc618b358ce15c07e7d103eef27aada2df45919b6f48eddbcb70b54796d8f679ab9972ddbead0547f8a6': 100
